image: debian/stable
packages:
  - python3
  - python3-pip
  - python3-setuptools
  - sqlite3
sources:
  - https://git.sr.ht/~tookmund/wmcoursescraper
tasks:
  - setup: |
      cd wmcoursescraper
      pip3 install -q -r requirements.txt

  - scrape: |
      cd wmcoursescraper
      python3 scraper.py

  - csv: |
      ./sqlite2csv.sh courses.db
