image: debian/stable
packages:
  - python3
  - python3-pip
  - python3-setuptools
sources:
  - https://git.sr.ht/~tookmund/wmcoursescraper
tasks:
  - setup: |
      cd wmcoursescraper
      pip3 install -q -r requirements.txt

  - test: |
      cd wmcoursescraper
      python3 scraper.py
